version: '3'
services:
  frichetten:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    command: ["./docker/wait-for-it.sh", "mongodb:27017", "--", "npm", "run", "serve:ssr"]  

  mongodb:
    image: "mongo"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "mongodata:/data/db"

volumes:
  mongodata:
