name = "hacker"
description = "Hack the Planet in style."
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
homepage = "https://github.com/frichetten/frichetten.github.io"
features = ["hacker","cybersecurity"]
min_version=0.14

[author]
    name = "Nick Frichette"
    homepage = "https://frichetten.com"
