name: Build Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Hugo
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.74.1/hugo_0.74.1_Linux-64bit.tar.gz && tar -xvf hugo_0.74.1_Linux-64bit.tar.gz
        
      - name: Build Website
        run: ./hugo --minify
