name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: hugo --minify

    - name: Copy Output
      run: |
        cp -r public/* /var/www/frichetten.com/
        sed -i 's|<url><loc>https://frichetten.com/categories/</loc></url>||g' /var/www/frichetten.com/sitemap.xml
        sed -i 's|<url><loc>https://frichetten.com/health/</loc><priority>0</priority></url>||g' /var/www/frichetten.com/sitemap.xml
        sed -i 's|<url><loc>https://frichetten.com/tags/</loc></url>||g' /var/www/frichetten.com/sitemap.xml
        sed -i 's|<url><loc>https://frichetten.com/acknowledgments/</loc></url>||g' /var/www/frichetten.com/sitemap.xml
